apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "2bbd7a1f-cec0-4e70-a387-6b20db26117e"
      - op: replace
        path: /spec/parameters/tenantId
        value: "3af986a9-762c-4c6c-91bb-7ab4916cb7d0"
  - target:
      kind: ObjectStore
      name: customer1-objectstore
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: "https://mercurybackupsstagingfl.blob.core.windows.net/customer1"
  - target:
      kind: Ingress
      name: customer1-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "customer1.mercury.fredericlefebvrecote.com"
      - op: replace
        path: /spec/rules/0/host
        value: "customer1.mercury.fredericlefebvrecote.com"
