apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "1c6d3cfd-4fb1-483d-9f97-8b4ff902a073"
      - op: replace
        path: /spec/parameters/tenantId
        value: "3af986a9-762c-4c6c-91bb-7ab4916cb7d0"
