apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "c728d9de-21a6-4f0b-8c1c-00c12147e8bb"
      - op: replace
        path: /spec/parameters/tenantId
        value: "3af986a9-762c-4c6c-91bb-7ab4916cb7d0"
  - target:
      kind: ObjectStore
      name: customer1-objectstore
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: "https://mercurybackupsfredlc.blob.core.windows.net/customer1"
