apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - secrets.yaml

patches:
  - target:
      kind: SecretProviderClass
      name: grafana-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "dc6c46dd-3f38-4609-9967-221f51111bf8"
      - op: replace
        path: /spec/parameters/keyvaultName
        value: "kv-mercury-prod-fl"
      - op: replace
        path: /spec/parameters/tenantId
        value: "3af986a9-762c-4c6c-91bb-7ab4916cb7d0"

configMapGenerator:
  - name: kube-prometheus-stack-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
