apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: julius-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - julius.mercury-prod.fredericlefebvrecote.com
      secretName: julius-tls
  rules:
    - host: julius.mercury-prod.fredericlefebvrecote.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: julius-n8n
                port:
                  number: 3008
